var l=a=>{throw TypeError(a)};var f=(a,r,n)=>r.has(a)||l("Cannot "+n);var c=(a,r,n)=>(f(a,r,"read from private field"),n?n.call(a):r.get(a)),m=(a,r,n)=>r.has(a)?l("Cannot add the same private member more than once"):r instanceof WeakSet?r.add(a):r.set(a,n);(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const t of o.addedNodes)t.tagName==="LINK"&&t.rel==="modulepreload"&&i(t)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();var s,d;class A{constructor(){m(this,s,"cAC0PQfupJc4LZexavuatT33ADOVunkK");m(this,d,"https://app.ticketmaster.com/discovery/v2/events.json");this.page=0,this.pageSize=12}getApiKey(){return c(this,s)}getBaseUrl(){return c(this,d)}async fetchEvents(){const r=new URLSearchParams({apikey:c(this,s),page:this.page,size:this.pageSize}),n=`${c(this,d)}?${r}&classificationName=music`,i=await fetch(n);if(!i.ok)throw new Error("Failed to fetch events");return i.json()}}s=new WeakMap,d=new WeakMap;function h(a){return a.map(n=>{var u,g;const i=((u=n.images[0])==null?void 0:u.url)||"",e=n.name||"No name avaible",o=n.dates.start.localDate||"Unknown Date",t=((g=n._embedded)==null?void 0:g.venues[0].name)||"Unknown Location",p=n.url||"#";return`
<li class="cards__item">
          <img src="${i}" alt="${e}" class="cards__img" />
          <h4 class="cards__event">${e}</h4>
          <p class="cards__date">${o}</p>
        <a href="${p}" target="_blank" rel="noopener noreferrer" class="cards__place">
          <img src="/img/place.svg" alt="" />
          ${t}
        </a>
      </li>
    `}).join("")}const E=document.getElementById("js-list"),y=new A;S();async function S(){var a;try{const n=((a=(await y.fetchEvents())._embedded)==null?void 0:a.events)||[],i=h(n);E.insertAdjacentHTML("beforeend",i)}catch(r){console.error(r)}}const v=document.getElementById("countryButton"),U=document.getElementById("countryList");v.addEventListener("click",()=>{U.click()});async function L(){try{let n=function(e){return r.filter(o=>o.region===e).map(o=>`<option value="${o.code}"><img src="${o.flag}" alt="${o.code}" class="flag__img"> ${o.name}</option>`).join("")};var a=n;const r=[{code:"US",name:"United States Of America",region:"NorthAmerica"},{code:"CA",name:"Canada",region:"NorthAmerica"},{code:"MX",name:"Mexico",region:"NorthAmerica"},{code:"AR",name:"Argentina",region:"SouthAmerica"},{code:"BR",name:"Brazil",region:"SouthAmerica"},{code:"CO",name:"Colombia",region:"SouthAmerica"},{code:"PE",name:"Peru",region:"SouthAmerica"},{code:"VE",name:"Venezuela",region:"SouthAmerica"},{code:"UY",name:"Uruguay",region:"SouthAmerica"},{code:"AT",name:"Austria",region:"Europe"},{code:"BE",name:"Belgium",region:"Europe"},{code:"BG",name:"Bulgaria",region:"Europe"},{code:"DE",name:"Germany",region:"Europe"},{code:"ES",name:"Spain",region:"Europe"},{code:"FR",name:"France",region:"Europe"},{code:"GB",name:"Great Britain",region:"Europe"},{code:"IT",name:"Italy",region:"Europe"},{code:"PL",name:"Poland",region:"Europe"},{code:"PT",name:"Portugal",region:"Europe"},{code:"RU",name:"Russia",region:"Europe"},{code:"SE",name:"Sweden",region:"Europe"},{code:"CN",name:"China",region:"Asia"},{code:"IN",name:"India",region:"Asia"},{code:"JP",name:"Japan",region:"Asia"},{code:"KR",name:"Korea, Republic of",region:"Asia"},{code:"SG",name:"Singapore",region:"Asia"},{code:"TH",name:"Thailand",region:"Asia"},{code:"TR",name:"Turkey",region:"Asia"},{code:"IL",name:"Israel",region:"Asia"},{code:"AE",name:"United Arab Emirates",region:"Asia"},{code:"SA",name:"Saudi Arabia",region:"Asia"},{code:"ZA",name:"South Africa",region:"Africa"},{code:"NG",name:"Nigeria",region:"Africa"},{code:"EG",name:"Egypt",region:"Africa"},{code:"KE",name:"Kenya",region:"Africa"},{code:"AU",name:"Australia",region:"Oceania"},{code:"NZ",name:"New Zealand",region:"Oceania"}];r.forEach(e=>{e.flag=`/imgs/header/flags/${e.code.toLowerCase()}.png`}),["Europe","NorthAmerica","SouthAmerica","Asia","Africa","Oceania"].forEach(e=>{const o=document.getElementById(e.toLowerCase());o&&(o.innerHTML=n(e))})}catch(r){console.error(r)}}L();
//# sourceMappingURL=index.js.map
